name: sharefood
description: "Plataforma de doação de alimentos - ShareFood"
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  # image_picker: ^1.1.2

  # Autenticação Google (se quiser login Google futuramente)
  google_sign_in: ^6.2.1

  # Utilitários
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: 0.20.2
  uuid: ^4.5.1
  async: ^2.11.0

  # Upload de imagens
  image_picker: ^1.1.2

  # Formatação de campos
  mask_text_input_formatter: 2.9.0
  flutter_masked_text2: ^0.9.1
  syncfusion_flutter_charts: ^31.1.23
  
  # URL
  url_launcher: ^6.3.0

  # Mapa
  # google_maps_flutter: ^2.6.1
  # geocoding: ^3.0.0

  # Ícones
  font_awesome_flutter: ^10.7.0

  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  rxdart: ^0.28.0 # Para programação reativa
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
